apiVersion: v1
kind: Service
metadata:
  name: drift-api-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: drift-api

  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP

  type: {{ .Values.api.service.type }}